EMS_MVC_30121023/Models/Department/DepartmentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace EMS_MVC_30121023.Models.Department
{
    public class DepartmentModel
    {
        public int DepartmentId { get; set; }

        
        [Required(ErrorMessage = "DepartmentCode is mandatory.")]
        [RegularExpression("[a-zA-Z]*",ErrorMessage ="Only Alphbets are allowed.")]
        [StringLength(6,ErrorMessage ="Max length is 6 character")]
        public string DepartmentCode { get; set; }

        [Required(ErrorMessage = "DepartmentName is mandatory")]
        [RegularExpression("[a-zA-Z\\s]*", ErrorMessage = "Only Alphbets are allowed.")]
        public string DepartmentName { get; set; }
    }
}

EMS_MVC_30121023/Models/Department/DepartmentRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;

namespace EMS_MVC_30121023.Models.Department
{
    public class DepartmentRepository
    {
        private string cs;
        public DepartmentRepository()
        {
          cs = ConfigurationManager.ConnectionStrings["DBCon"].ConnectionString;
        }
        public List<DepartmentModel> GetDepartments
        {
            //string cs = string.Empty;

            get
            {
                //return new List<DepartmentModel>()
                //                {
                //                    new DepartmentModel()
                //                    {
                //                        DepartmentId = 1,
                //                        DepartmentCode = "HR",
                //                        DepartmentName = "Human Resource"
                //                    },
                //                    new DepartmentModel()
                //                    {
                //                        DepartmentId = 2,
                //                        DepartmentCode = "MR",
                //                        DepartmentName = "Manager"
                //                    },
                //                    new DepartmentModel()
                //                    {
                //                        DepartmentId = 3,
                //                        DepartmentCode = "DPTR",
                //                        DepartmentName = "Department Manager"
                //                    }
                //                };


                List<DepartmentModel> models = new List<DepartmentModel>();
                SqlConnection con = new SqlConnection(cs);
                SqlCommand cmd = new SqlCommand("spGetAllDepartments", con);
                cmd.CommandType = CommandType.StoredProcedure;
                con.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                if (dr.HasRows)
                {
                    while (dr.Read())
                    {
                        models.Add(new DepartmentModel()
                        {
                            DepartmentId = Convert.ToInt32(dr["DepartmentId"]),
                            DepartmentCode = Convert.ToString(dr["DepartmentCode"]),
                            DepartmentName = Convert.ToString(dr["DepartmentName"])
                        });
                    }
                }
                con.Close();

                return models;
            }
        }


        public DepartmentModel GetDepartment(int DepartmentId)
        {
            SqlConnection con = new SqlConnection(cs);
            SqlCommand cmd = new SqlCommand("spGetDepartmentById", con);
            cmd.CommandType = CommandType.StoredProcedure;

            cmd.Parameters.AddWithValue("@DeptId", DepartmentId);

            DepartmentModel model = null;
            con.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                model = new DepartmentModel();
                while (dr.Read())
                {
                    model.DepartmentId = Convert.ToInt32(dr["Id"]);
                    model.DepartmentCode = Convert.ToString(dr["DeptCode"]);
                    model.DepartmentName = Convert.ToString(dr["DeptName"]);
                }
            }
            con.Close();

            return model;
        }

        public bool Save(DepartmentModel model,out string Message)
        {
            try
            {
                Message = string.Empty;
                string statuscode = string.Empty;
                using (SqlConnection con = new SqlConnection(cs))
                {
                    SqlCommand cmd = new SqlCommand("[spInsertDepartment]", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@DeptCode", model.DepartmentCode);
                    cmd.Parameters.AddWithValue("@DeptName", model.DepartmentName);

                    con.Open();
                    statuscode =  (string)cmd.ExecuteScalar();
                    con.Close();
                }

                if (statuscode == "S001")
                    return true;
                else if (statuscode == "RE01")
                    Message = "Record already exits";

                    return false;
            }
            catch (Exception ex)
            {
                Message = ex.Message;
                return false;
            }
        }

        public bool Update(DepartmentModel model, out string Message)
        {
            try
            {
                Message = string.Empty;
                string statuscode = string.Empty;
                using (SqlConnection con = new SqlConnection(cs))
                {
                    SqlCommand cmd = new SqlCommand("[spUpdateDepartment]", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@DeptId", model.DepartmentId);
                    cmd.Parameters.AddWithValue("@DeptCode", model.DepartmentCode);
                    cmd.Parameters.AddWithValue("@DeptName", model.DepartmentName);

                    con.Open();
                    statuscode = (string)cmd.ExecuteScalar();
                    con.Close();
                }

                if (statuscode == "U001")
                    return true;
                else if (statuscode == "RE01")
                    Message = "Record already exits";

                return false;
            }
            catch (Exception ex)
            {
                Message = ex.Message;
                return false;
            }
        }
        public bool Remove(int DepartmentId, out string Message)
        {
            try
            {
                Message = string.Empty;
                string statuscode = string.Empty;
                using (SqlConnection con = new SqlConnection(cs))
                {
                    SqlCommand cmd = new SqlCommand("[spRemoveDepartment]", con);
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@DepartmentId", DepartmentId);

                    con.Open();
                    statuscode = (string)cmd.ExecuteScalar();
                    con.Close();
                }

                if (statuscode == "S001")
                    return true;
                else if (statuscode == "RN01")
                    Message = "Record Not Found!";

                return false;
            }
            catch (Exception ex)
            {
                Message = ex.Message;
                return false;
            }
        }
    }
}

EMS_MVC_30121023/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using EMS_MVC_30121023.Models.Department;

namespace EMS_MVC_30121023.Controllers
{
    //Controller Lavel Filter
    //[Authorize]
    //[HandleError]
    public class DepartmentController : APPController
    {
        private readonly DepartmentRepository _repository;
        public DepartmentController()
        {
            _repository = new DepartmentRepository();
        }
        //Action
        //EndPoint
        [HttpGet]
        //Action Lavel Filter
        //[Authorize]

        [Route("")]
        [OutputCache(Duration =30)]
        public ViewResult Index()
        {
            //Session["Name"] = "Name";
            //ViewBag.Names = new string[] { "Option-1", "Option-2", "Option-3" };
            //ViewData["NamesD"] = new string[] { "Option-4", "Option-5", "Option-6" };
            //throw new Exception("CUstome error");
            var data = _repository.GetDepartments;
            return View(data);
        }

        [HttpGet]
        //[Route("AddDepartment")]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        //[ActionName("AddDepartment")]
        public ActionResult Create(DepartmentModel model)
        {
            if (ModelState.IsValid)
            {
                if (_repository.Save(model, out string errormessage))
                {
                    //var alertmessage = new
                    //{
                    //    Title = "Success Message",
                    //    Message = "Record Created Successfully!",
                    //    MessageType = "success"
                    //};

                    ////string message = "Record Created Successfully!";

                    //var JSConverter = new JavaScriptSerializer();
                    //TempData["Message"] = JSConverter.Serialize(alertmessage);

                    Notification("Sucees", "Record Create successfully",MessageType.success);
                    return RedirectToAction("Index");
                }
                else
                    Notification("Error", errormessage, MessageType.error);

            }

            return View();
        }


        [HttpGet]
        //[Route("ModifyDepartment/{id}")]
        public ActionResult Edit(int id)
        {
            DepartmentModel model = _repository.GetDepartment(id);
            if (model != null)
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        //[Route("ModifyDepartment")]
        public ActionResult Edit(DepartmentModel model)
        {
            if (_repository.Update(model, out string Message))
            {
                Notification("Sucees", "Record updated successfully", MessageType.success);

                return RedirectToAction("Index");
            }
            Notification("warning", Message, MessageType.warning);

            return View();
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            if (_repository.Remove(id, out string Message))
                Notification("Success", "Record delete successfully!", MessageType.success);
            else
                Notification("Error", Message, MessageType.error);

            return RedirectToAction("Index");
        }
    }
}

EMS_MVC_30121023/Views/Department/Create.cshtml
@model EMS_MVC_30121023.Models.Department.DepartmentModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <form  method="post">
        <div>
            <table>
                <tr>
                    <th>Department Code</th>
                    <td>
                        @*<input type="text" name="DepartmentCode" />*@
                        @*@Html.TextBox("DepartmentCode")*@
                        @Html.TextBoxFor(x => x.DepartmentCode)
                    </td>
                </tr>
                <tr>
                    <th>Department Name</th>
                    <td>
                        @*<input type="text" name="DepartmentName" />*@
                        @*@Html.TextBox("DepartmentName")*@
                        @Html.TextBoxFor(m => m.DepartmentName)
                    </td>
                    </td>
                </tr>
                <tr>
                    <th colspan="2">
                        <input type="submit" value="Save" />
                    </th>

                </tr>
            </table>
        </div>
        <div>
            <br />
            <span style="color:red">@ViewBag.Message</span>
        </div>
    </form>
  
</body>
</html>

EMS_MVC_30121023/Views/Department/Edit.cshtml
@model EMS_MVC_30121023.Models.Department.DepartmentModel
@*@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}*@


    <form method="post">
        <div>
            @Html.HiddenFor(x => x.DepartmentId)
            <table>
                <tr>
                    <th>Department Code</th>
                    <td>
                        @Html.TextBoxFor(x => x.DepartmentCode)
                    </td>
                </tr>
                <tr>
                    <th>Department Name</th>
                    <td>
                        @Html.TextBoxFor(m => m.DepartmentName)
                    </td>
                    </td>
                </tr>
                <tr>
                    <th colspan="2">
                        <input type="submit" value="Save" />
                    </th>

                </tr>
            </table>

        </div>
        <div>
            <br />
            <span style="color:red">@ViewBag.Message</span>
        </div>
    </form>

EMS_MVC_30121023/Views/Department/Index.cshtml
@model IEnumerable<EMS_MVC_30121023.Models.Department.DepartmentModel>

@*@{
        Layout = "~/Views/Shared/_Layout.cshtml";
    }*@


<div>

    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })

    <br />
    <table class="table">
        <thead>
            <tr>
                <th>Department Id</th>
                <th>Department Code</th>
                <th>Department Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.DepartmentId</td>
                        <td>@item.DepartmentCode</td>
                        <td>@item.DepartmentName</td>
                        <td>
                            @*<form method="post" action="Delete">
                                   @Html.Hidden("id",item.DepartmentId)
                                    <input type="submit" value="Remove" />
                                </form>*@

                            @using (Html.BeginForm("Delete", "Department", new { id = item.DepartmentId }, FormMethod.Post))
                            {

                                <div class="btn-group" role="group">
                                    <input type="submit" value="Remove" class="btn btn-sm btn-danger" />
                                    @Html.ActionLink("Edit", "Edit", new { id = item.DepartmentId }, new { @class = "btn btn-sm btn-primary" })

                                </div>

                            }
                        </td>
                        @*<td>
                              @Html.ActionLink("Remove","Delete",new {id= item.DepartmentId })
                            </td>*@
                        <td>
                            @*<a href="/Department/Edit/@item.DepartmentId">Edit</a>*@
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="3">
                        There is no data!
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @*@foreach (var item in Model)
        {
            <hr />
            <h3>
                Department Id : @item.DepartmentId
            </h3>
            <h3>
                Department Code : @item.DepartmentCode
            </h3>
            <h3>
                Department Name : @item.DepartmentName
            </h3>
            <hr />
        }*@

   
</div>

<hr />

   @*<ol>
       @foreach (var item in ViewBag.Names)
       {
           <li>@item</li>
       }
   </ol>

   <ol>
       @foreach (var item in (string[])ViewData["NamesD"])
       {
           <li>@item</li>
       }
   </ol>*@

@section Script{
      @Html.Partial("_Notifier")
    }